# Generated by Django 4.0.2 on 2022-02-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
