# Generated by Django 4.0.2 on 2022-02-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_api', '0003_remove_book_author_delete_author_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pob', models.CharField(max_length=10)),
                ('death_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('edition', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('idiom', models.CharField(max_length=20)),
                ('editorial', models.CharField(max_length=100)),
                ('author', models.ManyToManyField(to='library_api.Author')),
            ],
        ),
    ]
