# Generated by Django 4.0.2 on 2022-02-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pob',
            field=models.CharField(choices=[('C', 'Colombia'), ('E', 'Ecuador'), ('V', 'Venezuela')], max_length=1),
        ),
    ]
