# Generated by Django 4.0.2 on 2022-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_alter_author_pob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pob',
            field=models.CharField(max_length=10),
        ),
    ]
