# Generated by Django 4.0.2 on 2022-02-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0008_alter_author_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
